name: Go

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
      - name: Set up Go
        
      - name: Run tests
        run: go test -v .\tests\
        continue-on-error: false
